# For more info on HTTP files go to https://aka.ms/vs/httpfile
 

GET {{baseUrl}}/activity/get-all-activities

###
GET {{baseUrl}}/activity/11111111-1111-1111-1111-111111111111

###
POST {{baseUrl}}/activity/create-activity
Accept: application/json
Content-Type: application/json

{ 
  "name": "saeed",
  "fromAddress": "sender5@example.com",
  "toEmailAddress": "user5@example.com",
  "fromName": "Campaign5"
}

###
PUT {{baseUrl}}/activity/81272612-3155-4476-a90c-7e2183c3bdeb
Content-Type: application/json

{ 
  "name": "saeed5",
  "fromAddress": "sender5@example.com",
  "toEmailAddress": "user5@example.com",
  "fromName": "Campaign5",
  "openedDate" :  "2025-04-20T11:11:25.007283"
}

###
DELETE {{baseUrl}}/activity/14799e05-51d4-4d6f-8e42-74b3cd45fa4a