# For more info on HTTP files go to https://aka.ms/vs/httpfile
 

GET {{baseUrl}}/activity/get-all-activities

###
GET {{baseUrl}}/activity/11111111-1111-1111-1111-111111111111

###
POST {{baseUrl}}/activity/create-activity
Accept: application/json
Content-Type: application/json

{ 
  "name": "test",
  "fromAddress": "sender5@example.com",
  "toEmailAddress": "user5@example.com",
  "fromName": "Campaign5"
}

###
PUT {{baseUrl}}/activity/bd036630-3108-402d-b59a-d4e71522ac17
Content-Type: application/json

{
  "name":"test user",
  "fromAddress":"test@test2.com",
  "toEmailAddress":"test@test.com",
  "fromName":"test",
  "openedDate":"2025-04-23T21:30:00.000Z",
  "bouncedDate":"2025-04-22T20:00:00.000Z"
}

###
DELETE {{baseUrl}}/activity/14799e05-51d4-4d6f-8e42-74b3cd45fa4a